"""CPU fp32 reference generation with independently owned sequence state."""

import hashlib
import math
from dataclasses import dataclass, field

import torch
from torch import Tensor

from unearned.inference import KVCache, _same_state, _tensor_state, decode, prefill, validate_cache
from unearned.model import TransformerLM
from unearned.stopping import FunctionStop


@dataclass(frozen=True)
class GenerationConfig:
    """Greedy or full-distribution sampling; caps count sampled response tokens.

    Greedy ties select the lowest token ID and have log probability zero under
    that deterministic policy. Sampling uses fp32 softmax(logits/temperature),
    without truncation. Natural stops take precedence over token/context caps.
    """

    mode: str = 'greedy'
    temperature: float = 1.0
    max_new_tokens: int = 384
    eos_token_id: int | None = None
    top_p: float = field(default=1.0, init=False)

    def __post_init__(self):
        if self.mode not in ('greedy', 'sample'):
            raise ValueError('mode must be greedy or sample')
        if type(self.temperature) not in (int, float):
            raise TypeError('temperature must be a built-in number')
        if not math.isfinite(self.temperature) or self.temperature <= 0:
            raise ValueError('temperature must be finite and positive')
        if type(self.max_new_tokens) is not int or self.max_new_tokens < 0:
            raise ValueError('max_new_tokens must be a nonnegative integer')
        if self.eos_token_id is not None and (
            type(self.eos_token_id) is not int or self.eos_token_id < 0
        ):
            raise ValueError('eos_token_id must be a nonnegative integer or None')


def derive_seed(base_seed: int, slot_id: int) -> int:
    """SHA-256 v1 of two unsigned 64-bit IDs, independent of execution order.

    A caller assigns a stable logical slot ID to each prompt/completion pair.
    Recreating the same pair replays its stream; a new sample needs a new ID
    or base seed. This mapping is deterministic, not a collision-free guarantee.
    """
    for value in (base_seed, slot_id):
        if type(value) is not int or not 0 <= value < 2**64:
            raise ValueError('base_seed and slot_id must be unsigned 64-bit integers')
    payload = b'unearned-slot-v1\0' + base_seed.to_bytes(8, 'big') + slot_id.to_bytes(8, 'big')
    return int.from_bytes(hashlib.sha256(payload).digest()[:8], 'big')


@dataclass(frozen=True, eq=False)
class GenerationSlot:
    """Read-only snapshot; use start_slot to create or reuse a logical slot.

    For P prompt and N sampled tokens, cache.length is P+max(0,N-1).
    The latest sample is pending feedback, including a terminal sample. logits
    are [vocab] at the cached prefix and were used for that latest sample (or
    will select the first sample when N=0). No terminal token is silently fed.

    sampled_ids and decoded_bytes retain complete tokens, including EOS and
    bytes after a closing brace in the same token. output omits EOS spelling
    and clips at the function boundary. It contains generated bytes only;
    parser.source includes the separately supplied source prefix.

    Tensor ownership and supported model changes follow KVCache. Ordinary
    logits mutation is also rejected. Fields/private metadata must not be
    forged, and concurrent mutation and serialization are unsupported.
    """

    slot_id: int
    base_seed: int
    seed: int
    prompt_ids: tuple[int, ...]
    sampled_ids: tuple[int, ...]
    log_probs: tuple[float, ...]
    vocab: tuple[bytes, ...]
    config: GenerationConfig
    cache: KVCache
    logits: Tensor = field(repr=False)
    rng_state: bytes | None = field(repr=False)
    decoded_bytes: bytes
    output: bytes
    parser: FunctionStop | None
    prefix_length: int
    stop_reason: str | None
    _logits_state: tuple = field(repr=False)


def _cap_reason(config, prompt_length, sampled_length, context):
    if sampled_length >= config.max_new_tokens:
        return 'max_new_tokens'
    if prompt_length + sampled_length >= context:
        return 'context'
    return None


@torch.inference_mode(False)
@torch.no_grad()
def start_slot(
    model: TransformerLM, prompt_ids, *, vocab, slot_id: int,
    config: GenerationConfig = GenerationConfig(), base_seed: int = 0,
    function_prefix: bytes | None = None,
) -> GenerationSlot:
    """Prefill a nonempty token prompt, with no implicit BOS, padding or EOS.

    vocab snapshots token-ID-to-bytes, e.g. BPETokenizer.vocab. None disables
    lexical stopping; otherwise function_prefix is source only, excluding any
    instruction prose. A full context or zero budget returns stopped state.
    """
    if type(config) is not GenerationConfig:
        raise TypeError('config must be a GenerationConfig')
    seed = derive_seed(base_seed, slot_id)
    prompt = tuple(prompt_ids)
    if not prompt or any(type(token) is not int for token in prompt):
        raise ValueError('prompt_ids must be nonempty built-in integer IDs')
    vocabulary = tuple(vocab)
    if len(vocabulary) != model.config.vocab_size or any(
        type(piece) is not bytes or not piece for piece in vocabulary
    ):
        raise ValueError('vocab must contain one nonempty byte string per model token')
    if config.eos_token_id is not None and config.eos_token_id >= len(vocabulary):
        raise ValueError('eos_token_id is outside the vocabulary')
    parser = None if function_prefix is None else FunctionStop().feed(function_prefix)
    if parser is not None and parser.end is not None:
        raise ValueError('function_prefix already contains a completed body')
    logits, cache = prefill(model, torch.tensor([prompt], dtype=torch.int64, device='cpu'))
    last = logits[0, -1].clone()
    rng = None
    if config.mode == 'sample':
        generator = torch.Generator(device='cpu').manual_seed(seed)
        rng = bytes(generator.get_state().tolist())
    reason = _cap_reason(config, len(prompt), 0, model.config.max_seq_len)
    return GenerationSlot(
        slot_id, base_seed, seed, prompt, (), (), vocabulary, config, cache, last,
        rng, b'', b'', parser, 0 if function_prefix is None else len(function_prefix),
        reason, _tensor_state((last,)),
    )


def _validate_slot(model, slot):
    if type(slot) is not GenerationSlot:
        raise TypeError('slot must be a GenerationSlot returned by this API')
    # Terminal samples may skip decode, so validation must precede any draw.
    validate_cache(model, slot.cache)
    logits = slot.logits
    if (not isinstance(logits, Tensor) or logits.device.type != 'cpu'
            or logits.dtype != torch.float32 or logits.layout != torch.strided
            or logits.shape != (model.config.vocab_size,) or logits.requires_grad
            or logits.is_inference() or not _same_state((logits,), slot._logits_state)):
        raise ValueError('slot logits changed or do not match CPU fp32 vocabulary shape')
    if slot.cache.batch_size != 1 or slot.cache.length != len(slot.prompt_ids) + max(0, len(slot.sampled_ids) - 1):
        raise ValueError('slot cache length does not match its sampled history')


def _sample(logits, config, rng_state):
    if not torch.isfinite(logits).all():
        raise ValueError('sampling requires finite logits')
    if config.mode == 'greedy':
        return logits.argmax().item(), 0.0, None
    scaled = logits / config.temperature
    if not torch.isfinite(scaled).all():
        raise ValueError('temperature scaling produced nonfinite logits')
    probabilities = scaled.softmax(dim=-1)
    generator = torch.Generator(device='cpu')
    generator.set_state(torch.tensor(list(rng_state), dtype=torch.uint8, device='cpu'))
    token = torch.multinomial(probabilities, 1, generator=generator).item()
    return token, probabilities[token].log().item(), bytes(generator.get_state().tolist())


@torch.inference_mode(False)
@torch.no_grad()
def advance(model: TransformerLM, slot: GenerationSlot) -> GenerationSlot:
    """Sample once, publishing a new state only on success; stopped slots are unchanged.

    Exceptions, including KeyboardInterrupt, propagate with the original slot
    and global RNG unchanged. Retrying that slot replays its random draw.
    """
    _validate_slot(model, slot)
    if slot.stop_reason is not None:
        return slot
    cache, logits = slot.cache, slot.logits
    if slot.sampled_ids:
        prediction, cache = decode(model, torch.tensor([[slot.sampled_ids[-1]]],
                                                       dtype=torch.int64, device='cpu'), cache)
        logits = prediction[0, -1].clone()
    token, log_prob, rng = _sample(logits, slot.config, slot.rng_state)
    sampled = slot.sampled_ids + (token,)
    piece = slot.vocab[token]
    decoded = slot.decoded_bytes + piece
    parser = slot.parser
    if token == slot.config.eos_token_id:
        reason, output = 'eos', slot.output
    else:
        parser = None if parser is None else parser.feed(piece)
        output = decoded
        if parser is not None and parser.end is not None:
            reason = 'function'
            output = decoded[:parser.end - slot.prefix_length]
        else:
            reason = _cap_reason(slot.config, len(slot.prompt_ids), len(sampled), model.config.max_seq_len)
    return GenerationSlot(
        slot.slot_id, slot.base_seed, slot.seed, slot.prompt_ids, sampled,
        slot.log_probs + (log_prob,), slot.vocab, slot.config, cache, logits, rng,
        decoded, output, parser, slot.prefix_length, reason, _tensor_state((logits,)),
    )


def advance_slots(model: TransformerLM, slots) -> tuple[GenerationSlot, ...]:
    """Advance independent single-row slots in input order, without padding.

    Any failure leaves all incoming slots unchanged, including draws completed
    earlier in this call. Logical IDs must be unique within the supplied batch.
    """
    slots = tuple(slots)
    for slot in slots:
        _validate_slot(model, slot)
    if len({slot.slot_id for slot in slots}) != len(slots):
        raise ValueError('slot_id must be unique within a batch')
    return tuple(advance(model, slot) for slot in slots)


def generate(model: TransformerLM, slots) -> tuple[GenerationSlot, ...]:
    """Run the single-row reference batching policy until every slot stops."""
    states = advance_slots(model, slots)
    while any(slot.stop_reason is None for slot in states):
        states = advance_slots(model, states)
    return states
